# Python review

Short review about some core concepts in Python exemplified by objects in the Numpy library.
Goals:

- recall basic Python vocabulary
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:**

- core library for numerical computing in python
- many of libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import Numpy with its **standard abbreviation** `np`:

In [2]:
import numpy as np

## Variables

**variable:** a name we assign to a particular object in Python

In [3]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

To view a variable's value from our Jupyter notebook:

In [4]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: Use `snake_case` for naming variables.

This is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `myVariable`,
PEP 8 - Style Guide for Python Code recommends snake_case.

**Remember that variable names should both be descriptive and concise!**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind of object we have. 
We can also call the type of an object, the **class** of an object. So class and object both mena what kind of object we have.

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


In [10]:
# we can see the class/type of the function by using the `type`
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/data type of the NumPy package

In [9]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

`numpy.ndarray` is not the standard Python integer type `int`.

`numpy.ndarray` is a special data type in Numpy Telling us that 1 is an integer stored as a 64-bit number.

Check-in: access the value 5 in array `a`.

In [12]:
a[1,1]

5

## Functions

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create and **output**.

In the course we'll be using argument and parameter interchangeably. But they do have slightly different meanings.

We can ask for info about what a function does by executing ? followed by the function name:

In [13]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or a class, or module) works.

Notice that there are different types of arguments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments *you* have to specify for the function to work

- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parentheis () in the form `optional_argument = default_value`

Example

`end` is a parameter in `print` with default value a new line
We can pass the value `:-)` to this parameter so that it finished the line with `:-)` instead:

In [14]:
print('change the end parameter', end=':-)')

change the end parameter:-)

## Attributes and methods

An object in Python has attributese and methods.

- **attribute**: a property of the object, some piece of information oabout it.
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself.

In [15]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [17]:
# T is an example of an attribute, it returns the transpose of an array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [18]:
type(a.T)

numpy.ndarray

In [19]:
# Shape another attribute tells us the shappe of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [21]:
# ndim is an attribute holding the munber of array dimensions
print('dim:', a.ndim, '| type:', type(a.ndim))

dim: 2 | type: <class 'int'>


Attributes can have many different data types.

Some examples of methods.

In [22]:
# The min method returns the minimum value in the array along a specified axis
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [23]:
# Run min method with axiss
a.min()

1

Remember, methods are **functions** associated with an object. We can confirm this!

In [24]:
# method to list() transform array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [25]:
type(a.tolist)

builtin_function_or_method

## Exercise
1. Read the `print` function help. What is the type of the argument `sep`? sIs this a default or non-default arguemtn? why?

2. Create two new variaables, one with the integer value 77 and another one with the string 99.

3. Use your varialbes to print 77%99%77 by changing the value of one of the default arguments in `print`

In [26]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


sep is a string and default argument

In [27]:
num = 77
string_99 = '99'

In [29]:
print(num, string_99, num, sep= '%')

77%99%77
